#!/usr/bin/env bash

set -Eeuo pipefail

data_dir="${XDG_DATA_HOME:-${HOME}/.local/share}/bookmark"
mkdir -p "$data_dir"

bookmark_file="${BOOKMARK_FILE:-${data_dir}/bookmarks.json}"

print_version() {
	echo "Bookmark v0.2 - github.com/pierreprinetti/bookmark"
}

print_help() {
	echo -e "Manage bookmarks."
	echo
	echo -e "List bookmarks:"
	echo -e "\t${0}"
	echo
	echo -e "Add a new bookmark:"
	echo -e "\t${0} <url> <description>"
	echo
	echo -e "Print the database filename:"
	echo -e "\t${0} -F"
	echo
	echo -e "This help:"
	echo -e "\t${0} --help"
	echo
	echo -e "Print the version string:"
	echo -e "\t${0} --version"
}

# Build the JSON object representing the bookmark.
build() {
	local tags
	local out
	tags=()

	while getopts t: o; do
		case "$o" in
			t) tags+=("$OPTARG") ;;
			*) exit 1            ;;
		esac
	done

	shift "$((OPTIND-1))"

	local url="$1"
	out=$(echo '{}' | jq -c ".url=\"$url\"")

	if [ $# -gt 1 ]; then
		local description="$2"
		out="$(echo "$out" | jq -c ".description=\"$description\"")"
	fi

	for tag in "${tags[@]}"; do
		out="$(echo "$out" | jq -c ".tags += [\"$tag\"]")"
	done

	echo "$out"
}

# Add the bookmark to the database.
add() {
	build "$@" >> "$bookmark_file"
}

# Print the bookmark database filename.
print_bm_file(){
	echo "$bookmark_file"
}

if [ $# -eq 0 ]; then
	cat "$bookmark_file"
	exit 0
fi

case "$1" in
	-F)                print_bm_file ; exit 0 ;;
	-h|--help|help)    print_help    ; exit 0 ;;
	--version|version) print_version ; exit 0 ;;
esac

add "$@"
